version: '3.1'

services:

  opentheso:
    image: miledrousset/opentheso2
    restart: always
    depends_on:
      - opentheso2-db
    ports:
      - 8080:8080

  opentheso2-db:
    image: miledrouset/opentheso2-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: opentheso
      POSTGRES_PASSWORD: opentheso
      PGDATA: /pgdata
    volumes:
      - type: volume
        source: opentheso2-pgdata
        target: /pgdata

volumes:
  opentheso-pgdata:
    external: false