version: '3.1'

services:

  opentheso2-db:
    image: miledrousset/opentheso2-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: opentheso
      POSTGRES_PASSWORD: opentheso
      PGDATA: /pgdata
    volumes:
      - /docker-entrypoint-initdb.d/opentheso2-pgdata

  opentheso:
    image: miledrousset/opentheso2
    restart: always
    depends_on:
      - opentheso2-db
    ports:
      - 8080:8080

volumes:
  opentheso-pgdata:
    external: false